### ISSUE TITLE
NPN protocol does not work

### ISSUE THREAD

**Issue by michaelaw320** [HDE/aapns#10]
NPN protocol does not initialize even if openssl version is > 1.0.1 (default initialization without explicit ssl_context passing)

aapns version 19.1

Error log:
> The NPN extension requires OpenSSL 1.0.1 or later.

System:
Python 3.7.2 Docker, alpine 3.9 and alpine 3.8
openssl versions tested 1.0.2q on alpine 3.8
1.1.1a on alpine 3.9

NPN successfully initialized on mac with LibreSSL 2.6.5

**Comment by michaelaw320** [comment]
I thought we already dealt it with:
https://github.com/HDE/aapns/blob/62090b6fd7e01d98e02519f3f3aee66f1f88d111/src/aapns/api.py#L169-L172

**Comment by dimaqq** [comment]
Fixed in 07d5a91e0d2796583cdfcb1518689a4dfa39b509
